# Generated by Django 3.1 on 2020-08-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0003_auto_20200823_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='storename',
        ),
        migrations.RemoveField(
            model_name='item',
            name='storeurl',
        ),
        migrations.AddField(
            model_name='item',
            name='shopname',
            field=models.CharField(max_length=255, null=True, verbose_name='店名'),
        ),
        migrations.AddField(
            model_name='item',
            name='shopurl',
            field=models.CharField(max_length=1028, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.PositiveIntegerField(choices=[(1, 'black'), (2, 'white'), (3, 'blue'), (4, 'yellow'), (5, 'else')], verbose_name='色'),
        ),
    ]
